### PR TITLE
fix: return missing important information

### LINKED ISSUE #281: Warning output missed important information
After upgrading the uglifyjs-webpack-plugin dependency in webpack I noticied that the warnings format changed:

test result

* Before: single warning for an asset, After: each warning separate
* Before: info about the asset, After: information missing
* Before: note about UglifyJS, After: no info

I propose to merge warnings by module and add a not about asset and uglifyjs-webpack-plugin. Example:

```
WARNING in ./index.js in bundle.js (uglifyjs-webpack-plugin)
6,0: Dropping side-effect-free statement
8,0: Dropping unused function someUnUsedFunction1
9,0: Dropping unused function someUnUsedFunction2
10,0: Dropping unused function someUnUsedFunction3
11,0: Dropping unused function someUnUsedFunction4
12,0: Dropping unused function someUnUsedFunction5

WARNING in ./a.js in bundle.js (uglifyjs-webpack-plugin)
3,0: Dropping unused function someRemoteUnUsedFunction1
4,0: Dropping unused function someRemoteUnUsedFunction2
5,0: Dropping unused function someRemoteUnUsedFunction3
6,0: Dropping unused function someRemoteUnUsedFunction4
7,0: Dropping unused function someRemoteUnUsedFunction5
```

### PR DESCRIPTION
**Pull request by evilebottnawi**
fixes #281  

> Before: single warning for an asset, After: each warning separate
Before: info about the asset, After: information missing
Before: note about UglifyJS, After: no info

1. Each warning separate, it is allow filtering `compilation.warning` for plugins and who run webpack using own script (i have many questions in gitter how it is better do and one warning on an assets is best solution)
2. Add information about the asset
3. Add information about `UglifyJS`

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -106,7 +106,7 @@ class UglifyJsPlugin {
       }
     }
 
-    return warningMessage;
+    return `｢UglifyJs｣ ${warningMessage} in ${file}`;
```
Comment (ooflorent) [inline src/index.js]: Not sure about the brackets. `validateOptions` does not add them.

Comment (evilebottnawi) [reply src/index.js]: @ooflorent just use `UglifyJs`?

Comment (ooflorent) [reply src/index.js]: Maybe `UglifyJs Plugin` just as here: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/6ab091801ae4e9a0ef59dcab950717a98923a037/src/index.js#L21

**Comment by evilebottnawi** [comment]
@ooflorent done :+1:
